server:
  port: ${GATEWAY_APP_PORT}

spring:
  config:
    import: optional:configserver:http://${EUREKA_APP_HOST}:${EUREKA_APP_PORT}
  application:
    name: gateway-msvc
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://${STUDENT_APP_HOST}:${STUDENT_APP_PORT}
          predicates:
            - Path=/api/students/**
        - id: courses
          uri: http://${COURSE_APP_HOST}:${COURSE_APP_PORT}
          predicates:
            - Path=/api/courses/**